version: "3.7"

services:
  thin_node:
    image: tolar-node
    build:
      context: thin_node
    container_name: tolar-node
    network_mode: host
    restart: on-failure:5
    volumes:
    - keystore:/home/thin_node/.tolar/keystore/

  staging_node:
    image: staging-node
    build:
      context: staging_node
    container_name: staging-node
    network_mode: host
    restart: on-failure:5
    volumes:
      - staging:/home/thin_node/.tolar/keystore/

volumes:
  keystore:
  staging: