version: "3.7"

services:
  gateway:
    image: dreamfactoryhr/tolar-gateway
    container_name: gateway
    network_mode: host

  thin_node:
    image: thin_node
    build:
      context: thin_node
    container_name: thin_node
    network_mode: host