version: "2.4"

services:
  main_node:
    image: main-node
    build:
      context: main_node
    container_name: main-node
    ports:
      - 9201:9201
    restart: on-failure
    mem_limit: 2g
    volumes:
      - mainNet:/home/thin_node/.tolar/keystore/

  test_node:
    image: test-node
    build:
      context: test_node
    container_name: test-node
    ports:
      - 9202:9202
    restart: on-failure
    mem_limit: 2g
    volumes:
    - testNet:/home/thin_node/.tolar/keystore/

#  staging_node:
#    image: staging-node
#    build:
#      context: staging_node
#    container_name: staging-node
#    ports:
#      - 9203:9203
#    restart: on-failure
#    mem_limit: 2g
#    volumes:
#      - stagingNet:/home/thin_node/.tolar/keystore/

volumes:
  mainNet:
  testNet:
#  stagingNet: