version: "2.4"

services:
  thin_node:
    image: tolar-node
    build:
      context: thin_node
    container_name: tolar-node
    network_mode: host
    restart: on-failure
    mem_limit: 2g
    volumes:
    - testNet:/home/thin_node/.tolar/keystore/

#  staging_node:
#    image: staging-node
#    build:
#      context: staging_node
#    container_name: staging-node
#    network_mode: host
#    restart: on-failure
#    mem_limit: 2g
#    volumes:
#      - stagingNet:/home/thin_node/.tolar/keystore/

  main_node:
    image: main-node
    build:
      context: main_node
    container_name: main-node
    network_mode: host
    restart: on-failure
    mem_limit: 2g
    volumes:
      - mainNet:/home/thin_node/.tolar/keystore/

volumes:
  testNet:
  stagingNet:
  mainNet: