tolar-hashnet:
  host: ${TOLAR_HASHNET_HOST}
  port: ${TOLAR_HASHNET_PORT}
  channelCount: ${TOLAR_CHANNEL_COUNT}
  semaphorePermits: ${TOLAR_SEMAPHORE_PERMITS}
  semaphoreTimeout: ${TOLAR_SEMAPHORE_TIMEOUT}

server:
  undertow:
    threads:
      worker: 300