// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package io.tolar.proto;

import io.tolar.proto.tx.TransactionOuterClass;

public final class Client {
    private Client() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface SendTransactionRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.SendTransactionRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
         * @return Whether the transaction field is set.
         */
        boolean hasTransaction();
        /**
         * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
         * @return The transaction.
         */
        TransactionOuterClass.SignedTransaction getTransaction();
        /**
         * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
         */
        TransactionOuterClass.SignedTransactionOrBuilder getTransactionOrBuilder();
    }
    /**
     * Protobuf type {@code tolar.proto.SendTransactionRequest}
     */
    public  static final class SendTransactionRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.SendTransactionRequest)
            SendTransactionRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use SendTransactionRequest.newBuilder() to construct.
        private SendTransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private SendTransactionRequest() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SendTransactionRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private SendTransactionRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            TransactionOuterClass.SignedTransaction.Builder subBuilder = null;
                            if (transaction_ != null) {
                                subBuilder = transaction_.toBuilder();
                            }
                            transaction_ = input.readMessage(TransactionOuterClass.SignedTransaction.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(transaction_);
                                transaction_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Client.internal_static_tolar_proto_SendTransactionRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Client.internal_static_tolar_proto_SendTransactionRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Client.SendTransactionRequest.class, Client.SendTransactionRequest.Builder.class);
        }

        public static final int TRANSACTION_FIELD_NUMBER = 1;
        private TransactionOuterClass.SignedTransaction transaction_;
        /**
         * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
         * @return Whether the transaction field is set.
         */
        public boolean hasTransaction() {
            return transaction_ != null;
        }
        /**
         * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
         * @return The transaction.
         */
        public TransactionOuterClass.SignedTransaction getTransaction() {
            return transaction_ == null ? TransactionOuterClass.SignedTransaction.getDefaultInstance() : transaction_;
        }
        /**
         * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
         */
        public TransactionOuterClass.SignedTransactionOrBuilder getTransactionOrBuilder() {
            return getTransaction();
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (transaction_ != null) {
                output.writeMessage(1, getTransaction());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (transaction_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getTransaction());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Client.SendTransactionRequest)) {
                return super.equals(obj);
            }
            Client.SendTransactionRequest other = (Client.SendTransactionRequest) obj;

            if (hasTransaction() != other.hasTransaction()) return false;
            if (hasTransaction()) {
                if (!getTransaction()
                        .equals(other.getTransaction())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasTransaction()) {
                hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
                hash = (53 * hash) + getTransaction().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Client.SendTransactionRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendTransactionRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendTransactionRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendTransactionRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendTransactionRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendTransactionRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendTransactionRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Client.SendTransactionRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Client.SendTransactionRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Client.SendTransactionRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Client.SendTransactionRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Client.SendTransactionRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Client.SendTransactionRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.SendTransactionRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.SendTransactionRequest)
                Client.SendTransactionRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Client.internal_static_tolar_proto_SendTransactionRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Client.internal_static_tolar_proto_SendTransactionRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Client.SendTransactionRequest.class, Client.SendTransactionRequest.Builder.class);
            }

            // Construct using tolar.proto.Client.SendTransactionRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (transactionBuilder_ == null) {
                    transaction_ = null;
                } else {
                    transaction_ = null;
                    transactionBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Client.internal_static_tolar_proto_SendTransactionRequest_descriptor;
            }

            @java.lang.Override
            public Client.SendTransactionRequest getDefaultInstanceForType() {
                return Client.SendTransactionRequest.getDefaultInstance();
            }

            @java.lang.Override
            public Client.SendTransactionRequest build() {
                Client.SendTransactionRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Client.SendTransactionRequest buildPartial() {
                Client.SendTransactionRequest result = new Client.SendTransactionRequest(this);
                if (transactionBuilder_ == null) {
                    result.transaction_ = transaction_;
                } else {
                    result.transaction_ = transactionBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Client.SendTransactionRequest) {
                    return mergeFrom((Client.SendTransactionRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Client.SendTransactionRequest other) {
                if (other == Client.SendTransactionRequest.getDefaultInstance()) return this;
                if (other.hasTransaction()) {
                    mergeTransaction(other.getTransaction());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Client.SendTransactionRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Client.SendTransactionRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private TransactionOuterClass.SignedTransaction transaction_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder> transactionBuilder_;
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             * @return Whether the transaction field is set.
             */
            public boolean hasTransaction() {
                return transactionBuilder_ != null || transaction_ != null;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             * @return The transaction.
             */
            public TransactionOuterClass.SignedTransaction getTransaction() {
                if (transactionBuilder_ == null) {
                    return transaction_ == null ? TransactionOuterClass.SignedTransaction.getDefaultInstance() : transaction_;
                } else {
                    return transactionBuilder_.getMessage();
                }
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             */
            public Builder setTransaction(TransactionOuterClass.SignedTransaction value) {
                if (transactionBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    transaction_ = value;
                    onChanged();
                } else {
                    transactionBuilder_.setMessage(value);
                }

                return this;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             */
            public Builder setTransaction(
                    TransactionOuterClass.SignedTransaction.Builder builderForValue) {
                if (transactionBuilder_ == null) {
                    transaction_ = builderForValue.build();
                    onChanged();
                } else {
                    transactionBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             */
            public Builder mergeTransaction(TransactionOuterClass.SignedTransaction value) {
                if (transactionBuilder_ == null) {
                    if (transaction_ != null) {
                        transaction_ =
                                TransactionOuterClass.SignedTransaction.newBuilder(transaction_).mergeFrom(value).buildPartial();
                    } else {
                        transaction_ = value;
                    }
                    onChanged();
                } else {
                    transactionBuilder_.mergeFrom(value);
                }

                return this;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             */
            public Builder clearTransaction() {
                if (transactionBuilder_ == null) {
                    transaction_ = null;
                    onChanged();
                } else {
                    transaction_ = null;
                    transactionBuilder_ = null;
                }

                return this;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             */
            public TransactionOuterClass.SignedTransaction.Builder getTransactionBuilder() {

                onChanged();
                return getTransactionFieldBuilder().getBuilder();
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             */
            public TransactionOuterClass.SignedTransactionOrBuilder getTransactionOrBuilder() {
                if (transactionBuilder_ != null) {
                    return transactionBuilder_.getMessageOrBuilder();
                } else {
                    return transaction_ == null ?
                            TransactionOuterClass.SignedTransaction.getDefaultInstance() : transaction_;
                }
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction transaction = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder>
            getTransactionFieldBuilder() {
                if (transactionBuilder_ == null) {
                    transactionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder>(
                            getTransaction(),
                            getParentForChildren(),
                            isClean());
                    transaction_ = null;
                }
                return transactionBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.SendTransactionRequest)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.SendTransactionRequest)
        private static final Client.SendTransactionRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Client.SendTransactionRequest();
        }

        public static Client.SendTransactionRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SendTransactionRequest>
                PARSER = new com.google.protobuf.AbstractParser<SendTransactionRequest>() {
            @java.lang.Override
            public SendTransactionRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SendTransactionRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SendTransactionRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SendTransactionRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Client.SendTransactionRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SendTransactionResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.SendTransactionResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bool result = 1;</code>
         * @return The result.
         */
        boolean getResult();
    }
    /**
     * Protobuf type {@code tolar.proto.SendTransactionResponse}
     */
    public  static final class SendTransactionResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.SendTransactionResponse)
            SendTransactionResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use SendTransactionResponse.newBuilder() to construct.
        private SendTransactionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private SendTransactionResponse() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SendTransactionResponse();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private SendTransactionResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            result_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Client.internal_static_tolar_proto_SendTransactionResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Client.internal_static_tolar_proto_SendTransactionResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Client.SendTransactionResponse.class, Client.SendTransactionResponse.Builder.class);
        }

        public static final int RESULT_FIELD_NUMBER = 1;
        private boolean result_;
        /**
         * <code>bool result = 1;</code>
         * @return The result.
         */
        public boolean getResult() {
            return result_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (result_ != false) {
                output.writeBool(1, result_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (result_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, result_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Client.SendTransactionResponse)) {
                return super.equals(obj);
            }
            Client.SendTransactionResponse other = (Client.SendTransactionResponse) obj;

            if (getResult()
                    != other.getResult()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RESULT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getResult());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Client.SendTransactionResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendTransactionResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendTransactionResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendTransactionResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendTransactionResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendTransactionResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendTransactionResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Client.SendTransactionResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Client.SendTransactionResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Client.SendTransactionResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Client.SendTransactionResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Client.SendTransactionResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Client.SendTransactionResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.SendTransactionResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.SendTransactionResponse)
                Client.SendTransactionResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Client.internal_static_tolar_proto_SendTransactionResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Client.internal_static_tolar_proto_SendTransactionResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Client.SendTransactionResponse.class, Client.SendTransactionResponse.Builder.class);
            }

            // Construct using tolar.proto.Client.SendTransactionResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                result_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Client.internal_static_tolar_proto_SendTransactionResponse_descriptor;
            }

            @java.lang.Override
            public Client.SendTransactionResponse getDefaultInstanceForType() {
                return Client.SendTransactionResponse.getDefaultInstance();
            }

            @java.lang.Override
            public Client.SendTransactionResponse build() {
                Client.SendTransactionResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Client.SendTransactionResponse buildPartial() {
                Client.SendTransactionResponse result = new Client.SendTransactionResponse(this);
                result.result_ = result_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Client.SendTransactionResponse) {
                    return mergeFrom((Client.SendTransactionResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Client.SendTransactionResponse other) {
                if (other == Client.SendTransactionResponse.getDefaultInstance()) return this;
                if (other.getResult() != false) {
                    setResult(other.getResult());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Client.SendTransactionResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Client.SendTransactionResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private boolean result_ ;
            /**
             * <code>bool result = 1;</code>
             * @return The result.
             */
            public boolean getResult() {
                return result_;
            }
            /**
             * <code>bool result = 1;</code>
             * @param value The result to set.
             * @return This builder for chaining.
             */
            public Builder setResult(boolean value) {

                result_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bool result = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearResult() {

                result_ = false;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.SendTransactionResponse)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.SendTransactionResponse)
        private static final Client.SendTransactionResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Client.SendTransactionResponse();
        }

        public static Client.SendTransactionResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SendTransactionResponse>
                PARSER = new com.google.protobuf.AbstractParser<SendTransactionResponse>() {
            @java.lang.Override
            public SendTransactionResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SendTransactionResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SendTransactionResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SendTransactionResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Client.SendTransactionResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SendSignedTransactionRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.SendSignedTransactionRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
         * @return Whether the signedTransaction field is set.
         */
        boolean hasSignedTransaction();
        /**
         * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
         * @return The signedTransaction.
         */
        TransactionOuterClass.SignedTransaction getSignedTransaction();
        /**
         * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
         */
        TransactionOuterClass.SignedTransactionOrBuilder getSignedTransactionOrBuilder();
    }
    /**
     * Protobuf type {@code tolar.proto.SendSignedTransactionRequest}
     */
    public  static final class SendSignedTransactionRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.SendSignedTransactionRequest)
            SendSignedTransactionRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use SendSignedTransactionRequest.newBuilder() to construct.
        private SendSignedTransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private SendSignedTransactionRequest() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SendSignedTransactionRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private SendSignedTransactionRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            TransactionOuterClass.SignedTransaction.Builder subBuilder = null;
                            if (signedTransaction_ != null) {
                                subBuilder = signedTransaction_.toBuilder();
                            }
                            signedTransaction_ = input.readMessage(TransactionOuterClass.SignedTransaction.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(signedTransaction_);
                                signedTransaction_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Client.internal_static_tolar_proto_SendSignedTransactionRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Client.internal_static_tolar_proto_SendSignedTransactionRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Client.SendSignedTransactionRequest.class, Client.SendSignedTransactionRequest.Builder.class);
        }

        public static final int SIGNED_TRANSACTION_FIELD_NUMBER = 1;
        private TransactionOuterClass.SignedTransaction signedTransaction_;
        /**
         * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
         * @return Whether the signedTransaction field is set.
         */
        public boolean hasSignedTransaction() {
            return signedTransaction_ != null;
        }
        /**
         * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
         * @return The signedTransaction.
         */
        public TransactionOuterClass.SignedTransaction getSignedTransaction() {
            return signedTransaction_ == null ? TransactionOuterClass.SignedTransaction.getDefaultInstance() : signedTransaction_;
        }
        /**
         * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
         */
        public TransactionOuterClass.SignedTransactionOrBuilder getSignedTransactionOrBuilder() {
            return getSignedTransaction();
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (signedTransaction_ != null) {
                output.writeMessage(1, getSignedTransaction());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (signedTransaction_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getSignedTransaction());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Client.SendSignedTransactionRequest)) {
                return super.equals(obj);
            }
            Client.SendSignedTransactionRequest other = (Client.SendSignedTransactionRequest) obj;

            if (hasSignedTransaction() != other.hasSignedTransaction()) return false;
            if (hasSignedTransaction()) {
                if (!getSignedTransaction()
                        .equals(other.getSignedTransaction())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasSignedTransaction()) {
                hash = (37 * hash) + SIGNED_TRANSACTION_FIELD_NUMBER;
                hash = (53 * hash) + getSignedTransaction().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Client.SendSignedTransactionRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendSignedTransactionRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendSignedTransactionRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendSignedTransactionRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendSignedTransactionRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendSignedTransactionRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendSignedTransactionRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Client.SendSignedTransactionRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Client.SendSignedTransactionRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Client.SendSignedTransactionRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Client.SendSignedTransactionRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Client.SendSignedTransactionRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Client.SendSignedTransactionRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.SendSignedTransactionRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.SendSignedTransactionRequest)
                Client.SendSignedTransactionRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Client.internal_static_tolar_proto_SendSignedTransactionRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Client.internal_static_tolar_proto_SendSignedTransactionRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Client.SendSignedTransactionRequest.class, Client.SendSignedTransactionRequest.Builder.class);
            }

            // Construct using tolar.proto.Client.SendSignedTransactionRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (signedTransactionBuilder_ == null) {
                    signedTransaction_ = null;
                } else {
                    signedTransaction_ = null;
                    signedTransactionBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Client.internal_static_tolar_proto_SendSignedTransactionRequest_descriptor;
            }

            @java.lang.Override
            public Client.SendSignedTransactionRequest getDefaultInstanceForType() {
                return Client.SendSignedTransactionRequest.getDefaultInstance();
            }

            @java.lang.Override
            public Client.SendSignedTransactionRequest build() {
                Client.SendSignedTransactionRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Client.SendSignedTransactionRequest buildPartial() {
                Client.SendSignedTransactionRequest result = new Client.SendSignedTransactionRequest(this);
                if (signedTransactionBuilder_ == null) {
                    result.signedTransaction_ = signedTransaction_;
                } else {
                    result.signedTransaction_ = signedTransactionBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Client.SendSignedTransactionRequest) {
                    return mergeFrom((Client.SendSignedTransactionRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Client.SendSignedTransactionRequest other) {
                if (other == Client.SendSignedTransactionRequest.getDefaultInstance()) return this;
                if (other.hasSignedTransaction()) {
                    mergeSignedTransaction(other.getSignedTransaction());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Client.SendSignedTransactionRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Client.SendSignedTransactionRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private TransactionOuterClass.SignedTransaction signedTransaction_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder> signedTransactionBuilder_;
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             * @return Whether the signedTransaction field is set.
             */
            public boolean hasSignedTransaction() {
                return signedTransactionBuilder_ != null || signedTransaction_ != null;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             * @return The signedTransaction.
             */
            public TransactionOuterClass.SignedTransaction getSignedTransaction() {
                if (signedTransactionBuilder_ == null) {
                    return signedTransaction_ == null ? TransactionOuterClass.SignedTransaction.getDefaultInstance() : signedTransaction_;
                } else {
                    return signedTransactionBuilder_.getMessage();
                }
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             */
            public Builder setSignedTransaction(TransactionOuterClass.SignedTransaction value) {
                if (signedTransactionBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    signedTransaction_ = value;
                    onChanged();
                } else {
                    signedTransactionBuilder_.setMessage(value);
                }

                return this;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             */
            public Builder setSignedTransaction(
                    TransactionOuterClass.SignedTransaction.Builder builderForValue) {
                if (signedTransactionBuilder_ == null) {
                    signedTransaction_ = builderForValue.build();
                    onChanged();
                } else {
                    signedTransactionBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             */
            public Builder mergeSignedTransaction(TransactionOuterClass.SignedTransaction value) {
                if (signedTransactionBuilder_ == null) {
                    if (signedTransaction_ != null) {
                        signedTransaction_ =
                                TransactionOuterClass.SignedTransaction.newBuilder(signedTransaction_).mergeFrom(value).buildPartial();
                    } else {
                        signedTransaction_ = value;
                    }
                    onChanged();
                } else {
                    signedTransactionBuilder_.mergeFrom(value);
                }

                return this;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             */
            public Builder clearSignedTransaction() {
                if (signedTransactionBuilder_ == null) {
                    signedTransaction_ = null;
                    onChanged();
                } else {
                    signedTransaction_ = null;
                    signedTransactionBuilder_ = null;
                }

                return this;
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             */
            public TransactionOuterClass.SignedTransaction.Builder getSignedTransactionBuilder() {

                onChanged();
                return getSignedTransactionFieldBuilder().getBuilder();
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             */
            public TransactionOuterClass.SignedTransactionOrBuilder getSignedTransactionOrBuilder() {
                if (signedTransactionBuilder_ != null) {
                    return signedTransactionBuilder_.getMessageOrBuilder();
                } else {
                    return signedTransaction_ == null ?
                            TransactionOuterClass.SignedTransaction.getDefaultInstance() : signedTransaction_;
                }
            }
            /**
             * <code>.tolar.proto.tx.SignedTransaction signed_transaction = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder>
            getSignedTransactionFieldBuilder() {
                if (signedTransactionBuilder_ == null) {
                    signedTransactionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder>(
                            getSignedTransaction(),
                            getParentForChildren(),
                            isClean());
                    signedTransaction_ = null;
                }
                return signedTransactionBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.SendSignedTransactionRequest)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.SendSignedTransactionRequest)
        private static final Client.SendSignedTransactionRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Client.SendSignedTransactionRequest();
        }

        public static Client.SendSignedTransactionRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SendSignedTransactionRequest>
                PARSER = new com.google.protobuf.AbstractParser<SendSignedTransactionRequest>() {
            @java.lang.Override
            public SendSignedTransactionRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SendSignedTransactionRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SendSignedTransactionRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SendSignedTransactionRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Client.SendSignedTransactionRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SendSignedTransactionResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.SendSignedTransactionResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes transaction_hash = 1;</code>
         * @return The transactionHash.
         */
        com.google.protobuf.ByteString getTransactionHash();
    }
    /**
     * Protobuf type {@code tolar.proto.SendSignedTransactionResponse}
     */
    public  static final class SendSignedTransactionResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.SendSignedTransactionResponse)
            SendSignedTransactionResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use SendSignedTransactionResponse.newBuilder() to construct.
        private SendSignedTransactionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private SendSignedTransactionResponse() {
            transactionHash_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SendSignedTransactionResponse();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private SendSignedTransactionResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {

                            transactionHash_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Client.internal_static_tolar_proto_SendSignedTransactionResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Client.internal_static_tolar_proto_SendSignedTransactionResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Client.SendSignedTransactionResponse.class, Client.SendSignedTransactionResponse.Builder.class);
        }

        public static final int TRANSACTION_HASH_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString transactionHash_;
        /**
         * <code>bytes transaction_hash = 1;</code>
         * @return The transactionHash.
         */
        public com.google.protobuf.ByteString getTransactionHash() {
            return transactionHash_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!transactionHash_.isEmpty()) {
                output.writeBytes(1, transactionHash_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!transactionHash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, transactionHash_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Client.SendSignedTransactionResponse)) {
                return super.equals(obj);
            }
            Client.SendSignedTransactionResponse other = (Client.SendSignedTransactionResponse) obj;

            if (!getTransactionHash()
                    .equals(other.getTransactionHash())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TRANSACTION_HASH_FIELD_NUMBER;
            hash = (53 * hash) + getTransactionHash().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Client.SendSignedTransactionResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendSignedTransactionResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendSignedTransactionResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendSignedTransactionResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendSignedTransactionResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Client.SendSignedTransactionResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Client.SendSignedTransactionResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Client.SendSignedTransactionResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Client.SendSignedTransactionResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Client.SendSignedTransactionResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Client.SendSignedTransactionResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Client.SendSignedTransactionResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Client.SendSignedTransactionResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.SendSignedTransactionResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.SendSignedTransactionResponse)
                Client.SendSignedTransactionResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Client.internal_static_tolar_proto_SendSignedTransactionResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Client.internal_static_tolar_proto_SendSignedTransactionResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Client.SendSignedTransactionResponse.class, Client.SendSignedTransactionResponse.Builder.class);
            }

            // Construct using tolar.proto.Client.SendSignedTransactionResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                transactionHash_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Client.internal_static_tolar_proto_SendSignedTransactionResponse_descriptor;
            }

            @java.lang.Override
            public Client.SendSignedTransactionResponse getDefaultInstanceForType() {
                return Client.SendSignedTransactionResponse.getDefaultInstance();
            }

            @java.lang.Override
            public Client.SendSignedTransactionResponse build() {
                Client.SendSignedTransactionResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Client.SendSignedTransactionResponse buildPartial() {
                Client.SendSignedTransactionResponse result = new Client.SendSignedTransactionResponse(this);
                result.transactionHash_ = transactionHash_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Client.SendSignedTransactionResponse) {
                    return mergeFrom((Client.SendSignedTransactionResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Client.SendSignedTransactionResponse other) {
                if (other == Client.SendSignedTransactionResponse.getDefaultInstance()) return this;
                if (other.getTransactionHash() != com.google.protobuf.ByteString.EMPTY) {
                    setTransactionHash(other.getTransactionHash());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Client.SendSignedTransactionResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Client.SendSignedTransactionResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.ByteString transactionHash_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes transaction_hash = 1;</code>
             * @return The transactionHash.
             */
            public com.google.protobuf.ByteString getTransactionHash() {
                return transactionHash_;
            }
            /**
             * <code>bytes transaction_hash = 1;</code>
             * @param value The transactionHash to set.
             * @return This builder for chaining.
             */
            public Builder setTransactionHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                transactionHash_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes transaction_hash = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearTransactionHash() {

                transactionHash_ = getDefaultInstance().getTransactionHash();
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.SendSignedTransactionResponse)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.SendSignedTransactionResponse)
        private static final Client.SendSignedTransactionResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Client.SendSignedTransactionResponse();
        }

        public static Client.SendSignedTransactionResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SendSignedTransactionResponse>
                PARSER = new com.google.protobuf.AbstractParser<SendSignedTransactionResponse>() {
            @java.lang.Override
            public SendSignedTransactionResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SendSignedTransactionResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SendSignedTransactionResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SendSignedTransactionResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Client.SendSignedTransactionResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_SendTransactionRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_SendTransactionRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_SendTransactionResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_SendTransactionResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_SendSignedTransactionRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_SendSignedTransactionRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_SendSignedTransactionResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_SendSignedTransactionResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\014client.proto\022\013tolar.proto\032\035tolar/proto" +
                        "/transaction.proto\"P\n\026SendTransactionReq" +
                        "uest\0226\n\013transaction\030\001 \001(\0132!.tolar.proto." +
                        "tx.SignedTransaction\")\n\027SendTransactionR" +
                        "esponse\022\016\n\006result\030\001 \001(\010\"]\n\034SendSignedTra" +
                        "nsactionRequest\022=\n\022signed_transaction\030\001 " +
                        "\001(\0132!.tolar.proto.tx.SignedTransaction\"9" +
                        "\n\035SendSignedTransactionResponse\022\030\n\020trans" +
                        "action_hash\030\001 \001(\0142l\n\014TolarService\022\\\n\017Sen" +
                        "dTransaction\022#.tolar.proto.SendTransacti" +
                        "onRequest\032$.tolar.proto.SendTransactionR" +
                        "esponse2\204\001\n\022TransactionService\022n\n\025SendSi" +
                        "gnedTransaction\022).tolar.proto.SendSigned" +
                        "TransactionRequest\032*.tolar.proto.SendSig" +
                        "nedTransactionResponseb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                                TransactionOuterClass.getDescriptor(),
                        });
        internal_static_tolar_proto_SendTransactionRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tolar_proto_SendTransactionRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_SendTransactionRequest_descriptor,
                new java.lang.String[] { "Transaction", });
        internal_static_tolar_proto_SendTransactionResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_tolar_proto_SendTransactionResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_SendTransactionResponse_descriptor,
                new java.lang.String[] { "Result", });
        internal_static_tolar_proto_SendSignedTransactionRequest_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_tolar_proto_SendSignedTransactionRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_SendSignedTransactionRequest_descriptor,
                new java.lang.String[] { "SignedTransaction", });
        internal_static_tolar_proto_SendSignedTransactionResponse_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_tolar_proto_SendSignedTransactionResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_SendSignedTransactionResponse_descriptor,
                new java.lang.String[] { "TransactionHash", });
        TransactionOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}