// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tolar/proto/common.proto

package io.tolar.proto;

public final class Common {
    private Common() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface SignatureDataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.SignatureData)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes hash = 1;</code>
         * @return The hash.
         */
        com.google.protobuf.ByteString getHash();

        /**
         * <code>bytes signature = 2;</code>
         * @return The signature.
         */
        com.google.protobuf.ByteString getSignature();

        /**
         * <code>bytes signer_id = 3;</code>
         * @return The signerId.
         */
        com.google.protobuf.ByteString getSignerId();
    }
    /**
     * Protobuf type {@code tolar.proto.SignatureData}
     */
    public  static final class SignatureData extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.SignatureData)
            SignatureDataOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use SignatureData.newBuilder() to construct.
        private SignatureData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private SignatureData() {
            hash_ = com.google.protobuf.ByteString.EMPTY;
            signature_ = com.google.protobuf.ByteString.EMPTY;
            signerId_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SignatureData();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private SignatureData(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {

                            hash_ = input.readBytes();
                            break;
                        }
                        case 18: {

                            signature_ = input.readBytes();
                            break;
                        }
                        case 26: {

                            signerId_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Common.internal_static_tolar_proto_SignatureData_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Common.internal_static_tolar_proto_SignatureData_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Common.SignatureData.class, Common.SignatureData.Builder.class);
        }

        public static final int HASH_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString hash_;
        /**
         * <code>bytes hash = 1;</code>
         * @return The hash.
         */
        public com.google.protobuf.ByteString getHash() {
            return hash_;
        }

        public static final int SIGNATURE_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString signature_;
        /**
         * <code>bytes signature = 2;</code>
         * @return The signature.
         */
        public com.google.protobuf.ByteString getSignature() {
            return signature_;
        }

        public static final int SIGNER_ID_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString signerId_;
        /**
         * <code>bytes signer_id = 3;</code>
         * @return The signerId.
         */
        public com.google.protobuf.ByteString getSignerId() {
            return signerId_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!hash_.isEmpty()) {
                output.writeBytes(1, hash_);
            }
            if (!signature_.isEmpty()) {
                output.writeBytes(2, signature_);
            }
            if (!signerId_.isEmpty()) {
                output.writeBytes(3, signerId_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!hash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, hash_);
            }
            if (!signature_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, signature_);
            }
            if (!signerId_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, signerId_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Common.SignatureData)) {
                return super.equals(obj);
            }
            Common.SignatureData other = (Common.SignatureData) obj;

            if (!getHash()
                    .equals(other.getHash())) return false;
            if (!getSignature()
                    .equals(other.getSignature())) return false;
            if (!getSignerId()
                    .equals(other.getSignerId())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + HASH_FIELD_NUMBER;
            hash = (53 * hash) + getHash().hashCode();
            hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
            hash = (53 * hash) + getSignature().hashCode();
            hash = (37 * hash) + SIGNER_ID_FIELD_NUMBER;
            hash = (53 * hash) + getSignerId().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Common.SignatureData parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Common.SignatureData parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Common.SignatureData parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Common.SignatureData parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Common.SignatureData parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Common.SignatureData parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Common.SignatureData parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Common.SignatureData parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Common.SignatureData parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Common.SignatureData parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Common.SignatureData parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Common.SignatureData parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Common.SignatureData prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.SignatureData}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.SignatureData)
                Common.SignatureDataOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Common.internal_static_tolar_proto_SignatureData_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Common.internal_static_tolar_proto_SignatureData_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Common.SignatureData.class, Common.SignatureData.Builder.class);
            }

            // Construct using tolar.proto.Common.SignatureData.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                hash_ = com.google.protobuf.ByteString.EMPTY;

                signature_ = com.google.protobuf.ByteString.EMPTY;

                signerId_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Common.internal_static_tolar_proto_SignatureData_descriptor;
            }

            @java.lang.Override
            public Common.SignatureData getDefaultInstanceForType() {
                return Common.SignatureData.getDefaultInstance();
            }

            @java.lang.Override
            public Common.SignatureData build() {
                Common.SignatureData result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Common.SignatureData buildPartial() {
                Common.SignatureData result = new Common.SignatureData(this);
                result.hash_ = hash_;
                result.signature_ = signature_;
                result.signerId_ = signerId_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Common.SignatureData) {
                    return mergeFrom((Common.SignatureData)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Common.SignatureData other) {
                if (other == Common.SignatureData.getDefaultInstance()) return this;
                if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
                    setHash(other.getHash());
                }
                if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
                    setSignature(other.getSignature());
                }
                if (other.getSignerId() != com.google.protobuf.ByteString.EMPTY) {
                    setSignerId(other.getSignerId());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Common.SignatureData parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Common.SignatureData) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes hash = 1;</code>
             * @return The hash.
             */
            public com.google.protobuf.ByteString getHash() {
                return hash_;
            }
            /**
             * <code>bytes hash = 1;</code>
             * @param value The hash to set.
             * @return This builder for chaining.
             */
            public Builder setHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                hash_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes hash = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearHash() {

                hash_ = getDefaultInstance().getHash();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes signature = 2;</code>
             * @return The signature.
             */
            public com.google.protobuf.ByteString getSignature() {
                return signature_;
            }
            /**
             * <code>bytes signature = 2;</code>
             * @param value The signature to set.
             * @return This builder for chaining.
             */
            public Builder setSignature(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                signature_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes signature = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearSignature() {

                signature_ = getDefaultInstance().getSignature();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString signerId_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes signer_id = 3;</code>
             * @return The signerId.
             */
            public com.google.protobuf.ByteString getSignerId() {
                return signerId_;
            }
            /**
             * <code>bytes signer_id = 3;</code>
             * @param value The signerId to set.
             * @return This builder for chaining.
             */
            public Builder setSignerId(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                signerId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes signer_id = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearSignerId() {

                signerId_ = getDefaultInstance().getSignerId();
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.SignatureData)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.SignatureData)
        private static final Common.SignatureData DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Common.SignatureData();
        }

        public static Common.SignatureData getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SignatureData>
                PARSER = new com.google.protobuf.AbstractParser<SignatureData>() {
            @java.lang.Override
            public SignatureData parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SignatureData(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SignatureData> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SignatureData> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Common.SignatureData getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_SignatureData_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_SignatureData_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\030tolar/proto/common.proto\022\013tolar.proto\"" +
                        "C\n\rSignatureData\022\014\n\004hash\030\001 \001(\014\022\021\n\tsignat" +
                        "ure\030\002 \001(\014\022\021\n\tsigner_id\030\003 \001(\014b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_tolar_proto_SignatureData_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tolar_proto_SignatureData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_SignatureData_descriptor,
                new java.lang.String[] { "Hash", "Signature", "SignerId", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}