// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package io.tolar.proto;

import io.tolar.proto.tx.TransactionOuterClass;

public final class Core {
    private Core() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface EventOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.Event)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        java.util.List<TransactionOuterClass.SignedTransaction>
        getTransactionsList();
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        TransactionOuterClass.SignedTransaction getTransactions(int index);
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        int getTransactionsCount();
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        java.util.List<? extends TransactionOuterClass.SignedTransactionOrBuilder>
        getTransactionsOrBuilderList();
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        TransactionOuterClass.SignedTransactionOrBuilder getTransactionsOrBuilder(
                int index);

        /**
         * <code>bytes creator_node_id = 2;</code>
         * @return The creatorNodeId.
         */
        com.google.protobuf.ByteString getCreatorNodeId();

        /**
         * <code>bytes self_parent_hash = 3;</code>
         * @return The selfParentHash.
         */
        com.google.protobuf.ByteString getSelfParentHash();

        /**
         * <code>bytes other_parent_hash = 4;</code>
         * @return The otherParentHash.
         */
        com.google.protobuf.ByteString getOtherParentHash();

        /**
         * <pre>
         * nanoseconds since epoch
         * </pre>
         *
         * <code>uint64 timestamp = 5;</code>
         * @return The timestamp.
         */
        long getTimestamp();

        /**
         * <code>bytes last_block_hash = 6;</code>
         * @return The lastBlockHash.
         */
        com.google.protobuf.ByteString getLastBlockHash();

        /**
         * <code>uint64 index = 7;</code>
         * @return The index.
         */
        long getIndex();
    }
    /**
     * Protobuf type {@code tolar.proto.Event}
     */
    public  static final class Event extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.Event)
            EventOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Event.newBuilder() to construct.
        private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Event() {
            transactions_ = java.util.Collections.emptyList();
            creatorNodeId_ = com.google.protobuf.ByteString.EMPTY;
            selfParentHash_ = com.google.protobuf.ByteString.EMPTY;
            otherParentHash_ = com.google.protobuf.ByteString.EMPTY;
            lastBlockHash_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Event();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Event(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                transactions_ = new java.util.ArrayList<TransactionOuterClass.SignedTransaction>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            transactions_.add(
                                    input.readMessage(TransactionOuterClass.SignedTransaction.parser(), extensionRegistry));
                            break;
                        }
                        case 18: {

                            creatorNodeId_ = input.readBytes();
                            break;
                        }
                        case 26: {

                            selfParentHash_ = input.readBytes();
                            break;
                        }
                        case 34: {

                            otherParentHash_ = input.readBytes();
                            break;
                        }
                        case 40: {

                            timestamp_ = input.readUInt64();
                            break;
                        }
                        case 50: {

                            lastBlockHash_ = input.readBytes();
                            break;
                        }
                        case 56: {

                            index_ = input.readUInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    transactions_ = java.util.Collections.unmodifiableList(transactions_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Core.internal_static_tolar_proto_Event_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Core.internal_static_tolar_proto_Event_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Core.Event.class, Core.Event.Builder.class);
        }

        public static final int TRANSACTIONS_FIELD_NUMBER = 1;
        private java.util.List<TransactionOuterClass.SignedTransaction> transactions_;
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        public java.util.List<TransactionOuterClass.SignedTransaction> getTransactionsList() {
            return transactions_;
        }
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        public java.util.List<? extends TransactionOuterClass.SignedTransactionOrBuilder>
        getTransactionsOrBuilderList() {
            return transactions_;
        }
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        public int getTransactionsCount() {
            return transactions_.size();
        }
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        public TransactionOuterClass.SignedTransaction getTransactions(int index) {
            return transactions_.get(index);
        }
        /**
         * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
         */
        public TransactionOuterClass.SignedTransactionOrBuilder getTransactionsOrBuilder(
                int index) {
            return transactions_.get(index);
        }

        public static final int CREATOR_NODE_ID_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString creatorNodeId_;
        /**
         * <code>bytes creator_node_id = 2;</code>
         * @return The creatorNodeId.
         */
        public com.google.protobuf.ByteString getCreatorNodeId() {
            return creatorNodeId_;
        }

        public static final int SELF_PARENT_HASH_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString selfParentHash_;
        /**
         * <code>bytes self_parent_hash = 3;</code>
         * @return The selfParentHash.
         */
        public com.google.protobuf.ByteString getSelfParentHash() {
            return selfParentHash_;
        }

        public static final int OTHER_PARENT_HASH_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString otherParentHash_;
        /**
         * <code>bytes other_parent_hash = 4;</code>
         * @return The otherParentHash.
         */
        public com.google.protobuf.ByteString getOtherParentHash() {
            return otherParentHash_;
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 5;
        private long timestamp_;
        /**
         * <pre>
         * nanoseconds since epoch
         * </pre>
         *
         * <code>uint64 timestamp = 5;</code>
         * @return The timestamp.
         */
        public long getTimestamp() {
            return timestamp_;
        }

        public static final int LAST_BLOCK_HASH_FIELD_NUMBER = 6;
        private com.google.protobuf.ByteString lastBlockHash_;
        /**
         * <code>bytes last_block_hash = 6;</code>
         * @return The lastBlockHash.
         */
        public com.google.protobuf.ByteString getLastBlockHash() {
            return lastBlockHash_;
        }

        public static final int INDEX_FIELD_NUMBER = 7;
        private long index_;
        /**
         * <code>uint64 index = 7;</code>
         * @return The index.
         */
        public long getIndex() {
            return index_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < transactions_.size(); i++) {
                output.writeMessage(1, transactions_.get(i));
            }
            if (!creatorNodeId_.isEmpty()) {
                output.writeBytes(2, creatorNodeId_);
            }
            if (!selfParentHash_.isEmpty()) {
                output.writeBytes(3, selfParentHash_);
            }
            if (!otherParentHash_.isEmpty()) {
                output.writeBytes(4, otherParentHash_);
            }
            if (timestamp_ != 0L) {
                output.writeUInt64(5, timestamp_);
            }
            if (!lastBlockHash_.isEmpty()) {
                output.writeBytes(6, lastBlockHash_);
            }
            if (index_ != 0L) {
                output.writeUInt64(7, index_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < transactions_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, transactions_.get(i));
            }
            if (!creatorNodeId_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, creatorNodeId_);
            }
            if (!selfParentHash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, selfParentHash_);
            }
            if (!otherParentHash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, otherParentHash_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(5, timestamp_);
            }
            if (!lastBlockHash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(6, lastBlockHash_);
            }
            if (index_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(7, index_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Core.Event)) {
                return super.equals(obj);
            }
            Core.Event other = (Core.Event) obj;

            if (!getTransactionsList()
                    .equals(other.getTransactionsList())) return false;
            if (!getCreatorNodeId()
                    .equals(other.getCreatorNodeId())) return false;
            if (!getSelfParentHash()
                    .equals(other.getSelfParentHash())) return false;
            if (!getOtherParentHash()
                    .equals(other.getOtherParentHash())) return false;
            if (getTimestamp()
                    != other.getTimestamp()) return false;
            if (!getLastBlockHash()
                    .equals(other.getLastBlockHash())) return false;
            if (getIndex()
                    != other.getIndex()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getTransactionsCount() > 0) {
                hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
                hash = (53 * hash) + getTransactionsList().hashCode();
            }
            hash = (37 * hash) + CREATOR_NODE_ID_FIELD_NUMBER;
            hash = (53 * hash) + getCreatorNodeId().hashCode();
            hash = (37 * hash) + SELF_PARENT_HASH_FIELD_NUMBER;
            hash = (53 * hash) + getSelfParentHash().hashCode();
            hash = (37 * hash) + OTHER_PARENT_HASH_FIELD_NUMBER;
            hash = (53 * hash) + getOtherParentHash().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (37 * hash) + LAST_BLOCK_HASH_FIELD_NUMBER;
            hash = (53 * hash) + getLastBlockHash().hashCode();
            hash = (37 * hash) + INDEX_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getIndex());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Core.Event parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Core.Event parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Core.Event parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Core.Event parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Core.Event parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Core.Event parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Core.Event parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Core.Event parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Core.Event parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Core.Event parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Core.Event parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Core.Event parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Core.Event prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.Event}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.Event)
                Core.EventOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Core.internal_static_tolar_proto_Event_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Core.internal_static_tolar_proto_Event_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Core.Event.class, Core.Event.Builder.class);
            }

            // Construct using tolar.proto.Core.Event.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getTransactionsFieldBuilder();
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (transactionsBuilder_ == null) {
                    transactions_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    transactionsBuilder_.clear();
                }
                creatorNodeId_ = com.google.protobuf.ByteString.EMPTY;

                selfParentHash_ = com.google.protobuf.ByteString.EMPTY;

                otherParentHash_ = com.google.protobuf.ByteString.EMPTY;

                timestamp_ = 0L;

                lastBlockHash_ = com.google.protobuf.ByteString.EMPTY;

                index_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Core.internal_static_tolar_proto_Event_descriptor;
            }

            @java.lang.Override
            public Core.Event getDefaultInstanceForType() {
                return Core.Event.getDefaultInstance();
            }

            @java.lang.Override
            public Core.Event build() {
                Core.Event result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Core.Event buildPartial() {
                Core.Event result = new Core.Event(this);
                int from_bitField0_ = bitField0_;
                if (transactionsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        transactions_ = java.util.Collections.unmodifiableList(transactions_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.transactions_ = transactions_;
                } else {
                    result.transactions_ = transactionsBuilder_.build();
                }
                result.creatorNodeId_ = creatorNodeId_;
                result.selfParentHash_ = selfParentHash_;
                result.otherParentHash_ = otherParentHash_;
                result.timestamp_ = timestamp_;
                result.lastBlockHash_ = lastBlockHash_;
                result.index_ = index_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Core.Event) {
                    return mergeFrom((Core.Event)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Core.Event other) {
                if (other == Core.Event.getDefaultInstance()) return this;
                if (transactionsBuilder_ == null) {
                    if (!other.transactions_.isEmpty()) {
                        if (transactions_.isEmpty()) {
                            transactions_ = other.transactions_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureTransactionsIsMutable();
                            transactions_.addAll(other.transactions_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.transactions_.isEmpty()) {
                        if (transactionsBuilder_.isEmpty()) {
                            transactionsBuilder_.dispose();
                            transactionsBuilder_ = null;
                            transactions_ = other.transactions_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            transactionsBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getTransactionsFieldBuilder() : null;
                        } else {
                            transactionsBuilder_.addAllMessages(other.transactions_);
                        }
                    }
                }
                if (other.getCreatorNodeId() != com.google.protobuf.ByteString.EMPTY) {
                    setCreatorNodeId(other.getCreatorNodeId());
                }
                if (other.getSelfParentHash() != com.google.protobuf.ByteString.EMPTY) {
                    setSelfParentHash(other.getSelfParentHash());
                }
                if (other.getOtherParentHash() != com.google.protobuf.ByteString.EMPTY) {
                    setOtherParentHash(other.getOtherParentHash());
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                if (other.getLastBlockHash() != com.google.protobuf.ByteString.EMPTY) {
                    setLastBlockHash(other.getLastBlockHash());
                }
                if (other.getIndex() != 0L) {
                    setIndex(other.getIndex());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Core.Event parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Core.Event) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<TransactionOuterClass.SignedTransaction> transactions_ =
                    java.util.Collections.emptyList();
            private void ensureTransactionsIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    transactions_ = new java.util.ArrayList<TransactionOuterClass.SignedTransaction>(transactions_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder> transactionsBuilder_;

            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public java.util.List<TransactionOuterClass.SignedTransaction> getTransactionsList() {
                if (transactionsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(transactions_);
                } else {
                    return transactionsBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public int getTransactionsCount() {
                if (transactionsBuilder_ == null) {
                    return transactions_.size();
                } else {
                    return transactionsBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public TransactionOuterClass.SignedTransaction getTransactions(int index) {
                if (transactionsBuilder_ == null) {
                    return transactions_.get(index);
                } else {
                    return transactionsBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder setTransactions(
                    int index, TransactionOuterClass.SignedTransaction value) {
                if (transactionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTransactionsIsMutable();
                    transactions_.set(index, value);
                    onChanged();
                } else {
                    transactionsBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder setTransactions(
                    int index, TransactionOuterClass.SignedTransaction.Builder builderForValue) {
                if (transactionsBuilder_ == null) {
                    ensureTransactionsIsMutable();
                    transactions_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    transactionsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder addTransactions(TransactionOuterClass.SignedTransaction value) {
                if (transactionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTransactionsIsMutable();
                    transactions_.add(value);
                    onChanged();
                } else {
                    transactionsBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder addTransactions(
                    int index, TransactionOuterClass.SignedTransaction value) {
                if (transactionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTransactionsIsMutable();
                    transactions_.add(index, value);
                    onChanged();
                } else {
                    transactionsBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder addTransactions(
                    TransactionOuterClass.SignedTransaction.Builder builderForValue) {
                if (transactionsBuilder_ == null) {
                    ensureTransactionsIsMutable();
                    transactions_.add(builderForValue.build());
                    onChanged();
                } else {
                    transactionsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder addTransactions(
                    int index, TransactionOuterClass.SignedTransaction.Builder builderForValue) {
                if (transactionsBuilder_ == null) {
                    ensureTransactionsIsMutable();
                    transactions_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    transactionsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder addAllTransactions(
                    java.lang.Iterable<? extends TransactionOuterClass.SignedTransaction> values) {
                if (transactionsBuilder_ == null) {
                    ensureTransactionsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, transactions_);
                    onChanged();
                } else {
                    transactionsBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder clearTransactions() {
                if (transactionsBuilder_ == null) {
                    transactions_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    transactionsBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public Builder removeTransactions(int index) {
                if (transactionsBuilder_ == null) {
                    ensureTransactionsIsMutable();
                    transactions_.remove(index);
                    onChanged();
                } else {
                    transactionsBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public TransactionOuterClass.SignedTransaction.Builder getTransactionsBuilder(
                    int index) {
                return getTransactionsFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public TransactionOuterClass.SignedTransactionOrBuilder getTransactionsOrBuilder(
                    int index) {
                if (transactionsBuilder_ == null) {
                    return transactions_.get(index);  } else {
                    return transactionsBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public java.util.List<? extends TransactionOuterClass.SignedTransactionOrBuilder>
            getTransactionsOrBuilderList() {
                if (transactionsBuilder_ != null) {
                    return transactionsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(transactions_);
                }
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public TransactionOuterClass.SignedTransaction.Builder addTransactionsBuilder() {
                return getTransactionsFieldBuilder().addBuilder(
                        TransactionOuterClass.SignedTransaction.getDefaultInstance());
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public TransactionOuterClass.SignedTransaction.Builder addTransactionsBuilder(
                    int index) {
                return getTransactionsFieldBuilder().addBuilder(
                        index, TransactionOuterClass.SignedTransaction.getDefaultInstance());
            }
            /**
             * <code>repeated .tolar.proto.tx.SignedTransaction transactions = 1;</code>
             */
            public java.util.List<TransactionOuterClass.SignedTransaction.Builder>
            getTransactionsBuilderList() {
                return getTransactionsFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder>
            getTransactionsFieldBuilder() {
                if (transactionsBuilder_ == null) {
                    transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            TransactionOuterClass.SignedTransaction, TransactionOuterClass.SignedTransaction.Builder, TransactionOuterClass.SignedTransactionOrBuilder>(
                            transactions_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    transactions_ = null;
                }
                return transactionsBuilder_;
            }

            private com.google.protobuf.ByteString creatorNodeId_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes creator_node_id = 2;</code>
             * @return The creatorNodeId.
             */
            public com.google.protobuf.ByteString getCreatorNodeId() {
                return creatorNodeId_;
            }
            /**
             * <code>bytes creator_node_id = 2;</code>
             * @param value The creatorNodeId to set.
             * @return This builder for chaining.
             */
            public Builder setCreatorNodeId(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                creatorNodeId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes creator_node_id = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearCreatorNodeId() {

                creatorNodeId_ = getDefaultInstance().getCreatorNodeId();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString selfParentHash_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes self_parent_hash = 3;</code>
             * @return The selfParentHash.
             */
            public com.google.protobuf.ByteString getSelfParentHash() {
                return selfParentHash_;
            }
            /**
             * <code>bytes self_parent_hash = 3;</code>
             * @param value The selfParentHash to set.
             * @return This builder for chaining.
             */
            public Builder setSelfParentHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                selfParentHash_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes self_parent_hash = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearSelfParentHash() {

                selfParentHash_ = getDefaultInstance().getSelfParentHash();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString otherParentHash_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes other_parent_hash = 4;</code>
             * @return The otherParentHash.
             */
            public com.google.protobuf.ByteString getOtherParentHash() {
                return otherParentHash_;
            }
            /**
             * <code>bytes other_parent_hash = 4;</code>
             * @param value The otherParentHash to set.
             * @return This builder for chaining.
             */
            public Builder setOtherParentHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                otherParentHash_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes other_parent_hash = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearOtherParentHash() {

                otherParentHash_ = getDefaultInstance().getOtherParentHash();
                onChanged();
                return this;
            }

            private long timestamp_ ;
            /**
             * <pre>
             * nanoseconds since epoch
             * </pre>
             *
             * <code>uint64 timestamp = 5;</code>
             * @return The timestamp.
             */
            public long getTimestamp() {
                return timestamp_;
            }
            /**
             * <pre>
             * nanoseconds since epoch
             * </pre>
             *
             * <code>uint64 timestamp = 5;</code>
             * @param value The timestamp to set.
             * @return This builder for chaining.
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             * nanoseconds since epoch
             * </pre>
             *
             * <code>uint64 timestamp = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearTimestamp() {

                timestamp_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString lastBlockHash_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes last_block_hash = 6;</code>
             * @return The lastBlockHash.
             */
            public com.google.protobuf.ByteString getLastBlockHash() {
                return lastBlockHash_;
            }
            /**
             * <code>bytes last_block_hash = 6;</code>
             * @param value The lastBlockHash to set.
             * @return This builder for chaining.
             */
            public Builder setLastBlockHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                lastBlockHash_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes last_block_hash = 6;</code>
             * @return This builder for chaining.
             */
            public Builder clearLastBlockHash() {

                lastBlockHash_ = getDefaultInstance().getLastBlockHash();
                onChanged();
                return this;
            }

            private long index_ ;
            /**
             * <code>uint64 index = 7;</code>
             * @return The index.
             */
            public long getIndex() {
                return index_;
            }
            /**
             * <code>uint64 index = 7;</code>
             * @param value The index to set.
             * @return This builder for chaining.
             */
            public Builder setIndex(long value) {

                index_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>uint64 index = 7;</code>
             * @return This builder for chaining.
             */
            public Builder clearIndex() {

                index_ = 0L;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.Event)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.Event)
        private static final Core.Event DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Core.Event();
        }

        public static Core.Event getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Event>
                PARSER = new com.google.protobuf.AbstractParser<Event>() {
            @java.lang.Override
            public Event parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Event(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Event> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Event> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Core.Event getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SignedEventOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.SignedEvent)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.tolar.proto.Event body = 1;</code>
         * @return Whether the body field is set.
         */
        boolean hasBody();
        /**
         * <code>.tolar.proto.Event body = 1;</code>
         * @return The body.
         */
        Core.Event getBody();
        /**
         * <code>.tolar.proto.Event body = 1;</code>
         */
        Core.EventOrBuilder getBodyOrBuilder();

        /**
         * <code>.tolar.proto.SignatureData sig_data = 2;</code>
         * @return Whether the sigData field is set.
         */
        boolean hasSigData();
        /**
         * <code>.tolar.proto.SignatureData sig_data = 2;</code>
         * @return The sigData.
         */
        Common.SignatureData getSigData();
        /**
         * <code>.tolar.proto.SignatureData sig_data = 2;</code>
         */
        Common.SignatureDataOrBuilder getSigDataOrBuilder();
    }
    /**
     * Protobuf type {@code tolar.proto.SignedEvent}
     */
    public  static final class SignedEvent extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.SignedEvent)
            SignedEventOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use SignedEvent.newBuilder() to construct.
        private SignedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private SignedEvent() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SignedEvent();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private SignedEvent(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            Core.Event.Builder subBuilder = null;
                            if (body_ != null) {
                                subBuilder = body_.toBuilder();
                            }
                            body_ = input.readMessage(Core.Event.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(body_);
                                body_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            Common.SignatureData.Builder subBuilder = null;
                            if (sigData_ != null) {
                                subBuilder = sigData_.toBuilder();
                            }
                            sigData_ = input.readMessage(Common.SignatureData.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(sigData_);
                                sigData_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Core.internal_static_tolar_proto_SignedEvent_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Core.internal_static_tolar_proto_SignedEvent_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Core.SignedEvent.class, Core.SignedEvent.Builder.class);
        }

        public static final int BODY_FIELD_NUMBER = 1;
        private Core.Event body_;
        /**
         * <code>.tolar.proto.Event body = 1;</code>
         * @return Whether the body field is set.
         */
        public boolean hasBody() {
            return body_ != null;
        }
        /**
         * <code>.tolar.proto.Event body = 1;</code>
         * @return The body.
         */
        public Core.Event getBody() {
            return body_ == null ? Core.Event.getDefaultInstance() : body_;
        }
        /**
         * <code>.tolar.proto.Event body = 1;</code>
         */
        public Core.EventOrBuilder getBodyOrBuilder() {
            return getBody();
        }

        public static final int SIG_DATA_FIELD_NUMBER = 2;
        private Common.SignatureData sigData_;
        /**
         * <code>.tolar.proto.SignatureData sig_data = 2;</code>
         * @return Whether the sigData field is set.
         */
        public boolean hasSigData() {
            return sigData_ != null;
        }
        /**
         * <code>.tolar.proto.SignatureData sig_data = 2;</code>
         * @return The sigData.
         */
        public Common.SignatureData getSigData() {
            return sigData_ == null ? Common.SignatureData.getDefaultInstance() : sigData_;
        }
        /**
         * <code>.tolar.proto.SignatureData sig_data = 2;</code>
         */
        public Common.SignatureDataOrBuilder getSigDataOrBuilder() {
            return getSigData();
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (body_ != null) {
                output.writeMessage(1, getBody());
            }
            if (sigData_ != null) {
                output.writeMessage(2, getSigData());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (body_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getBody());
            }
            if (sigData_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getSigData());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Core.SignedEvent)) {
                return super.equals(obj);
            }
            Core.SignedEvent other = (Core.SignedEvent) obj;

            if (hasBody() != other.hasBody()) return false;
            if (hasBody()) {
                if (!getBody()
                        .equals(other.getBody())) return false;
            }
            if (hasSigData() != other.hasSigData()) return false;
            if (hasSigData()) {
                if (!getSigData()
                        .equals(other.getSigData())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasBody()) {
                hash = (37 * hash) + BODY_FIELD_NUMBER;
                hash = (53 * hash) + getBody().hashCode();
            }
            if (hasSigData()) {
                hash = (37 * hash) + SIG_DATA_FIELD_NUMBER;
                hash = (53 * hash) + getSigData().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Core.SignedEvent parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Core.SignedEvent parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Core.SignedEvent parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Core.SignedEvent parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Core.SignedEvent parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Core.SignedEvent parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Core.SignedEvent parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Core.SignedEvent parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Core.SignedEvent parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Core.SignedEvent parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Core.SignedEvent parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Core.SignedEvent parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Core.SignedEvent prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.SignedEvent}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.SignedEvent)
                Core.SignedEventOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Core.internal_static_tolar_proto_SignedEvent_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Core.internal_static_tolar_proto_SignedEvent_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Core.SignedEvent.class, Core.SignedEvent.Builder.class);
            }

            // Construct using tolar.proto.Core.SignedEvent.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (bodyBuilder_ == null) {
                    body_ = null;
                } else {
                    body_ = null;
                    bodyBuilder_ = null;
                }
                if (sigDataBuilder_ == null) {
                    sigData_ = null;
                } else {
                    sigData_ = null;
                    sigDataBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Core.internal_static_tolar_proto_SignedEvent_descriptor;
            }

            @java.lang.Override
            public Core.SignedEvent getDefaultInstanceForType() {
                return Core.SignedEvent.getDefaultInstance();
            }

            @java.lang.Override
            public Core.SignedEvent build() {
                Core.SignedEvent result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Core.SignedEvent buildPartial() {
                Core.SignedEvent result = new Core.SignedEvent(this);
                if (bodyBuilder_ == null) {
                    result.body_ = body_;
                } else {
                    result.body_ = bodyBuilder_.build();
                }
                if (sigDataBuilder_ == null) {
                    result.sigData_ = sigData_;
                } else {
                    result.sigData_ = sigDataBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Core.SignedEvent) {
                    return mergeFrom((Core.SignedEvent)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Core.SignedEvent other) {
                if (other == Core.SignedEvent.getDefaultInstance()) return this;
                if (other.hasBody()) {
                    mergeBody(other.getBody());
                }
                if (other.hasSigData()) {
                    mergeSigData(other.getSigData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Core.SignedEvent parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Core.SignedEvent) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Core.Event body_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    Core.Event, Core.Event.Builder, Core.EventOrBuilder> bodyBuilder_;
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             * @return Whether the body field is set.
             */
            public boolean hasBody() {
                return bodyBuilder_ != null || body_ != null;
            }
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             * @return The body.
             */
            public Core.Event getBody() {
                if (bodyBuilder_ == null) {
                    return body_ == null ? Core.Event.getDefaultInstance() : body_;
                } else {
                    return bodyBuilder_.getMessage();
                }
            }
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             */
            public Builder setBody(Core.Event value) {
                if (bodyBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    body_ = value;
                    onChanged();
                } else {
                    bodyBuilder_.setMessage(value);
                }

                return this;
            }
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             */
            public Builder setBody(
                    Core.Event.Builder builderForValue) {
                if (bodyBuilder_ == null) {
                    body_ = builderForValue.build();
                    onChanged();
                } else {
                    bodyBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             */
            public Builder mergeBody(Core.Event value) {
                if (bodyBuilder_ == null) {
                    if (body_ != null) {
                        body_ =
                                Core.Event.newBuilder(body_).mergeFrom(value).buildPartial();
                    } else {
                        body_ = value;
                    }
                    onChanged();
                } else {
                    bodyBuilder_.mergeFrom(value);
                }

                return this;
            }
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             */
            public Builder clearBody() {
                if (bodyBuilder_ == null) {
                    body_ = null;
                    onChanged();
                } else {
                    body_ = null;
                    bodyBuilder_ = null;
                }

                return this;
            }
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             */
            public Core.Event.Builder getBodyBuilder() {

                onChanged();
                return getBodyFieldBuilder().getBuilder();
            }
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             */
            public Core.EventOrBuilder getBodyOrBuilder() {
                if (bodyBuilder_ != null) {
                    return bodyBuilder_.getMessageOrBuilder();
                } else {
                    return body_ == null ?
                            Core.Event.getDefaultInstance() : body_;
                }
            }
            /**
             * <code>.tolar.proto.Event body = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    Core.Event, Core.Event.Builder, Core.EventOrBuilder>
            getBodyFieldBuilder() {
                if (bodyBuilder_ == null) {
                    bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            Core.Event, Core.Event.Builder, Core.EventOrBuilder>(
                            getBody(),
                            getParentForChildren(),
                            isClean());
                    body_ = null;
                }
                return bodyBuilder_;
            }

            private Common.SignatureData sigData_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    Common.SignatureData, Common.SignatureData.Builder, Common.SignatureDataOrBuilder> sigDataBuilder_;
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             * @return Whether the sigData field is set.
             */
            public boolean hasSigData() {
                return sigDataBuilder_ != null || sigData_ != null;
            }
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             * @return The sigData.
             */
            public Common.SignatureData getSigData() {
                if (sigDataBuilder_ == null) {
                    return sigData_ == null ? Common.SignatureData.getDefaultInstance() : sigData_;
                } else {
                    return sigDataBuilder_.getMessage();
                }
            }
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             */
            public Builder setSigData(Common.SignatureData value) {
                if (sigDataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    sigData_ = value;
                    onChanged();
                } else {
                    sigDataBuilder_.setMessage(value);
                }

                return this;
            }
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             */
            public Builder setSigData(
                    Common.SignatureData.Builder builderForValue) {
                if (sigDataBuilder_ == null) {
                    sigData_ = builderForValue.build();
                    onChanged();
                } else {
                    sigDataBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             */
            public Builder mergeSigData(Common.SignatureData value) {
                if (sigDataBuilder_ == null) {
                    if (sigData_ != null) {
                        sigData_ =
                                Common.SignatureData.newBuilder(sigData_).mergeFrom(value).buildPartial();
                    } else {
                        sigData_ = value;
                    }
                    onChanged();
                } else {
                    sigDataBuilder_.mergeFrom(value);
                }

                return this;
            }
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             */
            public Builder clearSigData() {
                if (sigDataBuilder_ == null) {
                    sigData_ = null;
                    onChanged();
                } else {
                    sigData_ = null;
                    sigDataBuilder_ = null;
                }

                return this;
            }
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             */
            public Common.SignatureData.Builder getSigDataBuilder() {

                onChanged();
                return getSigDataFieldBuilder().getBuilder();
            }
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             */
            public Common.SignatureDataOrBuilder getSigDataOrBuilder() {
                if (sigDataBuilder_ != null) {
                    return sigDataBuilder_.getMessageOrBuilder();
                } else {
                    return sigData_ == null ?
                            Common.SignatureData.getDefaultInstance() : sigData_;
                }
            }
            /**
             * <code>.tolar.proto.SignatureData sig_data = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    Common.SignatureData, Common.SignatureData.Builder, Common.SignatureDataOrBuilder>
            getSigDataFieldBuilder() {
                if (sigDataBuilder_ == null) {
                    sigDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            Common.SignatureData, Common.SignatureData.Builder, Common.SignatureDataOrBuilder>(
                            getSigData(),
                            getParentForChildren(),
                            isClean());
                    sigData_ = null;
                }
                return sigDataBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.SignedEvent)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.SignedEvent)
        private static final Core.SignedEvent DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Core.SignedEvent();
        }

        public static Core.SignedEvent getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SignedEvent>
                PARSER = new com.google.protobuf.AbstractParser<SignedEvent>() {
            @java.lang.Override
            public SignedEvent parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SignedEvent(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SignedEvent> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SignedEvent> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Core.SignedEvent getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_Event_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_Event_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_SignedEvent_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_SignedEvent_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\ncore.proto\022\013tolar.proto\032\030tolar/proto/c" +
                        "ommon.proto\032\035tolar/proto/transaction.pro" +
                        "to\"\311\001\n\005Event\0227\n\014transactions\030\001 \003(\0132!.tol" +
                        "ar.proto.tx.SignedTransaction\022\027\n\017creator" +
                        "_node_id\030\002 \001(\014\022\030\n\020self_parent_hash\030\003 \001(\014" +
                        "\022\031\n\021other_parent_hash\030\004 \001(\014\022\021\n\ttimestamp" +
                        "\030\005 \001(\004\022\027\n\017last_block_hash\030\006 \001(\014\022\r\n\005index" +
                        "\030\007 \001(\004\"]\n\013SignedEvent\022 \n\004body\030\001 \001(\0132\022.to" +
                        "lar.proto.Event\022,\n\010sig_data\030\002 \001(\0132\032.tola" +
                        "r.proto.SignatureDatab\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                                Common.getDescriptor(),
                                TransactionOuterClass.getDescriptor(),
                        });
        internal_static_tolar_proto_Event_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tolar_proto_Event_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_Event_descriptor,
                new java.lang.String[] { "Transactions", "CreatorNodeId", "SelfParentHash", "OtherParentHash", "Timestamp", "LastBlockHash", "Index", });
        internal_static_tolar_proto_SignedEvent_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_tolar_proto_SignedEvent_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_SignedEvent_descriptor,
                new java.lang.String[] { "Body", "SigData", });
        Common.getDescriptor();
        TransactionOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}