// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: version.proto

package io.tolar.proto;

public final class Version {
    private Version() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface VersionRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.VersionRequest)
            com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code tolar.proto.VersionRequest}
     */
    public  static final class VersionRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.VersionRequest)
            VersionRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use VersionRequest.newBuilder() to construct.
        private VersionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private VersionRequest() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new VersionRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private VersionRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Version.internal_static_tolar_proto_VersionRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Version.internal_static_tolar_proto_VersionRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Version.VersionRequest.class, Version.VersionRequest.Builder.class);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Version.VersionRequest)) {
                return super.equals(obj);
            }
            Version.VersionRequest other = (Version.VersionRequest) obj;

            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Version.VersionRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.VersionRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.VersionRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.VersionRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.VersionRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.VersionRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.VersionRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Version.VersionRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Version.VersionRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Version.VersionRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Version.VersionRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Version.VersionRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Version.VersionRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.VersionRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.VersionRequest)
                Version.VersionRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Version.internal_static_tolar_proto_VersionRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Version.internal_static_tolar_proto_VersionRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Version.VersionRequest.class, Version.VersionRequest.Builder.class);
            }

            // Construct using tolar.proto.Version.VersionRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Version.internal_static_tolar_proto_VersionRequest_descriptor;
            }

            @java.lang.Override
            public Version.VersionRequest getDefaultInstanceForType() {
                return Version.VersionRequest.getDefaultInstance();
            }

            @java.lang.Override
            public Version.VersionRequest build() {
                Version.VersionRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Version.VersionRequest buildPartial() {
                Version.VersionRequest result = new Version.VersionRequest(this);
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Version.VersionRequest) {
                    return mergeFrom((Version.VersionRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Version.VersionRequest other) {
                if (other == Version.VersionRequest.getDefaultInstance()) return this;
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Version.VersionRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Version.VersionRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.VersionRequest)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.VersionRequest)
        private static final Version.VersionRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Version.VersionRequest();
        }

        public static Version.VersionRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<VersionRequest>
                PARSER = new com.google.protobuf.AbstractParser<VersionRequest>() {
            @java.lang.Override
            public VersionRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new VersionRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<VersionRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<VersionRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Version.VersionRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface VersionResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.VersionResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 version = 1;</code>
         * @return The version.
         */
        long getVersion();

        /**
         * <code>uint32 major_version = 2;</code>
         * @return The majorVersion.
         */
        int getMajorVersion();

        /**
         * <code>uint32 minor_version = 3;</code>
         * @return The minorVersion.
         */
        int getMinorVersion();

        /**
         * <code>uint32 patch_number = 4;</code>
         * @return The patchNumber.
         */
        int getPatchNumber();
    }
    /**
     * Protobuf type {@code tolar.proto.VersionResponse}
     */
    public  static final class VersionResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.VersionResponse)
            VersionResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use VersionResponse.newBuilder() to construct.
        private VersionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private VersionResponse() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new VersionResponse();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private VersionResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            version_ = input.readUInt64();
                            break;
                        }
                        case 16: {

                            majorVersion_ = input.readUInt32();
                            break;
                        }
                        case 24: {

                            minorVersion_ = input.readUInt32();
                            break;
                        }
                        case 32: {

                            patchNumber_ = input.readUInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Version.internal_static_tolar_proto_VersionResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Version.internal_static_tolar_proto_VersionResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Version.VersionResponse.class, Version.VersionResponse.Builder.class);
        }

        public static final int VERSION_FIELD_NUMBER = 1;
        private long version_;
        /**
         * <code>uint64 version = 1;</code>
         * @return The version.
         */
        public long getVersion() {
            return version_;
        }

        public static final int MAJOR_VERSION_FIELD_NUMBER = 2;
        private int majorVersion_;
        /**
         * <code>uint32 major_version = 2;</code>
         * @return The majorVersion.
         */
        public int getMajorVersion() {
            return majorVersion_;
        }

        public static final int MINOR_VERSION_FIELD_NUMBER = 3;
        private int minorVersion_;
        /**
         * <code>uint32 minor_version = 3;</code>
         * @return The minorVersion.
         */
        public int getMinorVersion() {
            return minorVersion_;
        }

        public static final int PATCH_NUMBER_FIELD_NUMBER = 4;
        private int patchNumber_;
        /**
         * <code>uint32 patch_number = 4;</code>
         * @return The patchNumber.
         */
        public int getPatchNumber() {
            return patchNumber_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (version_ != 0L) {
                output.writeUInt64(1, version_);
            }
            if (majorVersion_ != 0) {
                output.writeUInt32(2, majorVersion_);
            }
            if (minorVersion_ != 0) {
                output.writeUInt32(3, minorVersion_);
            }
            if (patchNumber_ != 0) {
                output.writeUInt32(4, patchNumber_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (version_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, version_);
            }
            if (majorVersion_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, majorVersion_);
            }
            if (minorVersion_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, minorVersion_);
            }
            if (patchNumber_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(4, patchNumber_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Version.VersionResponse)) {
                return super.equals(obj);
            }
            Version.VersionResponse other = (Version.VersionResponse) obj;

            if (getVersion()
                    != other.getVersion()) return false;
            if (getMajorVersion()
                    != other.getMajorVersion()) return false;
            if (getMinorVersion()
                    != other.getMinorVersion()) return false;
            if (getPatchNumber()
                    != other.getPatchNumber()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + VERSION_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getVersion());
            hash = (37 * hash) + MAJOR_VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getMajorVersion();
            hash = (37 * hash) + MINOR_VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getMinorVersion();
            hash = (37 * hash) + PATCH_NUMBER_FIELD_NUMBER;
            hash = (53 * hash) + getPatchNumber();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Version.VersionResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.VersionResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.VersionResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.VersionResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.VersionResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.VersionResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.VersionResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Version.VersionResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Version.VersionResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Version.VersionResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Version.VersionResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Version.VersionResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Version.VersionResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.VersionResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.VersionResponse)
                Version.VersionResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Version.internal_static_tolar_proto_VersionResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Version.internal_static_tolar_proto_VersionResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Version.VersionResponse.class, Version.VersionResponse.Builder.class);
            }

            // Construct using tolar.proto.Version.VersionResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                version_ = 0L;

                majorVersion_ = 0;

                minorVersion_ = 0;

                patchNumber_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Version.internal_static_tolar_proto_VersionResponse_descriptor;
            }

            @java.lang.Override
            public Version.VersionResponse getDefaultInstanceForType() {
                return Version.VersionResponse.getDefaultInstance();
            }

            @java.lang.Override
            public Version.VersionResponse build() {
                Version.VersionResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Version.VersionResponse buildPartial() {
                Version.VersionResponse result = new Version.VersionResponse(this);
                result.version_ = version_;
                result.majorVersion_ = majorVersion_;
                result.minorVersion_ = minorVersion_;
                result.patchNumber_ = patchNumber_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Version.VersionResponse) {
                    return mergeFrom((Version.VersionResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Version.VersionResponse other) {
                if (other == Version.VersionResponse.getDefaultInstance()) return this;
                if (other.getVersion() != 0L) {
                    setVersion(other.getVersion());
                }
                if (other.getMajorVersion() != 0) {
                    setMajorVersion(other.getMajorVersion());
                }
                if (other.getMinorVersion() != 0) {
                    setMinorVersion(other.getMinorVersion());
                }
                if (other.getPatchNumber() != 0) {
                    setPatchNumber(other.getPatchNumber());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Version.VersionResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Version.VersionResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long version_ ;
            /**
             * <code>uint64 version = 1;</code>
             * @return The version.
             */
            public long getVersion() {
                return version_;
            }
            /**
             * <code>uint64 version = 1;</code>
             * @param value The version to set.
             * @return This builder for chaining.
             */
            public Builder setVersion(long value) {

                version_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>uint64 version = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearVersion() {

                version_ = 0L;
                onChanged();
                return this;
            }

            private int majorVersion_ ;
            /**
             * <code>uint32 major_version = 2;</code>
             * @return The majorVersion.
             */
            public int getMajorVersion() {
                return majorVersion_;
            }
            /**
             * <code>uint32 major_version = 2;</code>
             * @param value The majorVersion to set.
             * @return This builder for chaining.
             */
            public Builder setMajorVersion(int value) {

                majorVersion_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>uint32 major_version = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearMajorVersion() {

                majorVersion_ = 0;
                onChanged();
                return this;
            }

            private int minorVersion_ ;
            /**
             * <code>uint32 minor_version = 3;</code>
             * @return The minorVersion.
             */
            public int getMinorVersion() {
                return minorVersion_;
            }
            /**
             * <code>uint32 minor_version = 3;</code>
             * @param value The minorVersion to set.
             * @return This builder for chaining.
             */
            public Builder setMinorVersion(int value) {

                minorVersion_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>uint32 minor_version = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearMinorVersion() {

                minorVersion_ = 0;
                onChanged();
                return this;
            }

            private int patchNumber_ ;
            /**
             * <code>uint32 patch_number = 4;</code>
             * @return The patchNumber.
             */
            public int getPatchNumber() {
                return patchNumber_;
            }
            /**
             * <code>uint32 patch_number = 4;</code>
             * @param value The patchNumber to set.
             * @return This builder for chaining.
             */
            public Builder setPatchNumber(int value) {

                patchNumber_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>uint32 patch_number = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearPatchNumber() {

                patchNumber_ = 0;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.VersionResponse)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.VersionResponse)
        private static final Version.VersionResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Version.VersionResponse();
        }

        public static Version.VersionResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<VersionResponse>
                PARSER = new com.google.protobuf.AbstractParser<VersionResponse>() {
            @java.lang.Override
            public VersionResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new VersionResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<VersionResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<VersionResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Version.VersionResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ProtocolVersionRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.ProtocolVersionRequest)
            com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code tolar.proto.ProtocolVersionRequest}
     */
    public  static final class ProtocolVersionRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.ProtocolVersionRequest)
            ProtocolVersionRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use ProtocolVersionRequest.newBuilder() to construct.
        private ProtocolVersionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private ProtocolVersionRequest() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ProtocolVersionRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private ProtocolVersionRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Version.internal_static_tolar_proto_ProtocolVersionRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Version.internal_static_tolar_proto_ProtocolVersionRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Version.ProtocolVersionRequest.class, Version.ProtocolVersionRequest.Builder.class);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Version.ProtocolVersionRequest)) {
                return super.equals(obj);
            }
            Version.ProtocolVersionRequest other = (Version.ProtocolVersionRequest) obj;

            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Version.ProtocolVersionRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.ProtocolVersionRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.ProtocolVersionRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.ProtocolVersionRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.ProtocolVersionRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.ProtocolVersionRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.ProtocolVersionRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Version.ProtocolVersionRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Version.ProtocolVersionRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Version.ProtocolVersionRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Version.ProtocolVersionRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Version.ProtocolVersionRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Version.ProtocolVersionRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.ProtocolVersionRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.ProtocolVersionRequest)
                Version.ProtocolVersionRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Version.internal_static_tolar_proto_ProtocolVersionRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Version.internal_static_tolar_proto_ProtocolVersionRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Version.ProtocolVersionRequest.class, Version.ProtocolVersionRequest.Builder.class);
            }

            // Construct using tolar.proto.Version.ProtocolVersionRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Version.internal_static_tolar_proto_ProtocolVersionRequest_descriptor;
            }

            @java.lang.Override
            public Version.ProtocolVersionRequest getDefaultInstanceForType() {
                return Version.ProtocolVersionRequest.getDefaultInstance();
            }

            @java.lang.Override
            public Version.ProtocolVersionRequest build() {
                Version.ProtocolVersionRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Version.ProtocolVersionRequest buildPartial() {
                Version.ProtocolVersionRequest result = new Version.ProtocolVersionRequest(this);
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Version.ProtocolVersionRequest) {
                    return mergeFrom((Version.ProtocolVersionRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Version.ProtocolVersionRequest other) {
                if (other == Version.ProtocolVersionRequest.getDefaultInstance()) return this;
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Version.ProtocolVersionRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Version.ProtocolVersionRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.ProtocolVersionRequest)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.ProtocolVersionRequest)
        private static final Version.ProtocolVersionRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Version.ProtocolVersionRequest();
        }

        public static Version.ProtocolVersionRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ProtocolVersionRequest>
                PARSER = new com.google.protobuf.AbstractParser<ProtocolVersionRequest>() {
            @java.lang.Override
            public ProtocolVersionRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ProtocolVersionRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ProtocolVersionRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ProtocolVersionRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Version.ProtocolVersionRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ProtocolVersionResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tolar.proto.ProtocolVersionResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 protocol_version = 1;</code>
         * @return The protocolVersion.
         */
        long getProtocolVersion();
    }
    /**
     * Protobuf type {@code tolar.proto.ProtocolVersionResponse}
     */
    public  static final class ProtocolVersionResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tolar.proto.ProtocolVersionResponse)
            ProtocolVersionResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use ProtocolVersionResponse.newBuilder() to construct.
        private ProtocolVersionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private ProtocolVersionResponse() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ProtocolVersionResponse();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private ProtocolVersionResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            protocolVersion_ = input.readUInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Version.internal_static_tolar_proto_ProtocolVersionResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Version.internal_static_tolar_proto_ProtocolVersionResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Version.ProtocolVersionResponse.class, Version.ProtocolVersionResponse.Builder.class);
        }

        public static final int PROTOCOL_VERSION_FIELD_NUMBER = 1;
        private long protocolVersion_;
        /**
         * <code>uint64 protocol_version = 1;</code>
         * @return The protocolVersion.
         */
        public long getProtocolVersion() {
            return protocolVersion_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (protocolVersion_ != 0L) {
                output.writeUInt64(1, protocolVersion_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (protocolVersion_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, protocolVersion_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Version.ProtocolVersionResponse)) {
                return super.equals(obj);
            }
            Version.ProtocolVersionResponse other = (Version.ProtocolVersionResponse) obj;

            if (getProtocolVersion()
                    != other.getProtocolVersion()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getProtocolVersion());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Version.ProtocolVersionResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.ProtocolVersionResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.ProtocolVersionResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.ProtocolVersionResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.ProtocolVersionResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Version.ProtocolVersionResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Version.ProtocolVersionResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Version.ProtocolVersionResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Version.ProtocolVersionResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Version.ProtocolVersionResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Version.ProtocolVersionResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Version.ProtocolVersionResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Version.ProtocolVersionResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code tolar.proto.ProtocolVersionResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tolar.proto.ProtocolVersionResponse)
                Version.ProtocolVersionResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Version.internal_static_tolar_proto_ProtocolVersionResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Version.internal_static_tolar_proto_ProtocolVersionResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Version.ProtocolVersionResponse.class, Version.ProtocolVersionResponse.Builder.class);
            }

            // Construct using tolar.proto.Version.ProtocolVersionResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                protocolVersion_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Version.internal_static_tolar_proto_ProtocolVersionResponse_descriptor;
            }

            @java.lang.Override
            public Version.ProtocolVersionResponse getDefaultInstanceForType() {
                return Version.ProtocolVersionResponse.getDefaultInstance();
            }

            @java.lang.Override
            public Version.ProtocolVersionResponse build() {
                Version.ProtocolVersionResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Version.ProtocolVersionResponse buildPartial() {
                Version.ProtocolVersionResponse result = new Version.ProtocolVersionResponse(this);
                result.protocolVersion_ = protocolVersion_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Version.ProtocolVersionResponse) {
                    return mergeFrom((Version.ProtocolVersionResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Version.ProtocolVersionResponse other) {
                if (other == Version.ProtocolVersionResponse.getDefaultInstance()) return this;
                if (other.getProtocolVersion() != 0L) {
                    setProtocolVersion(other.getProtocolVersion());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Version.ProtocolVersionResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Version.ProtocolVersionResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long protocolVersion_ ;
            /**
             * <code>uint64 protocol_version = 1;</code>
             * @return The protocolVersion.
             */
            public long getProtocolVersion() {
                return protocolVersion_;
            }
            /**
             * <code>uint64 protocol_version = 1;</code>
             * @param value The protocolVersion to set.
             * @return This builder for chaining.
             */
            public Builder setProtocolVersion(long value) {

                protocolVersion_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>uint64 protocol_version = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearProtocolVersion() {

                protocolVersion_ = 0L;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tolar.proto.ProtocolVersionResponse)
        }

        // @@protoc_insertion_point(class_scope:tolar.proto.ProtocolVersionResponse)
        private static final Version.ProtocolVersionResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Version.ProtocolVersionResponse();
        }

        public static Version.ProtocolVersionResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ProtocolVersionResponse>
                PARSER = new com.google.protobuf.AbstractParser<ProtocolVersionResponse>() {
            @java.lang.Override
            public ProtocolVersionResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ProtocolVersionResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ProtocolVersionResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ProtocolVersionResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Version.ProtocolVersionResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_VersionRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_VersionRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_VersionResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_VersionResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_ProtocolVersionRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_ProtocolVersionRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tolar_proto_ProtocolVersionResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tolar_proto_ProtocolVersionResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rversion.proto\022\013tolar.proto\"\020\n\016VersionR" +
                        "equest\"f\n\017VersionResponse\022\017\n\007version\030\001 \001" +
                        "(\004\022\025\n\rmajor_version\030\002 \001(\r\022\025\n\rminor_versi" +
                        "on\030\003 \001(\r\022\024\n\014patch_number\030\004 \001(\r\"\030\n\026Protoc" +
                        "olVersionRequest\"3\n\027ProtocolVersionRespo" +
                        "nse\022\030\n\020protocol_version\030\001 \001(\0042\264\001\n\016Versio" +
                        "nService\022D\n\007Version\022\033.tolar.proto.Versio" +
                        "nRequest\032\034.tolar.proto.VersionResponse\022\\" +
                        "\n\017ProtocolVersion\022#.tolar.proto.Protocol" +
                        "VersionRequest\032$.tolar.proto.ProtocolVer" +
                        "sionResponseb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_tolar_proto_VersionRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tolar_proto_VersionRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_VersionRequest_descriptor,
                new java.lang.String[] { });
        internal_static_tolar_proto_VersionResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_tolar_proto_VersionResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_VersionResponse_descriptor,
                new java.lang.String[] { "Version", "MajorVersion", "MinorVersion", "PatchNumber", });
        internal_static_tolar_proto_ProtocolVersionRequest_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_tolar_proto_ProtocolVersionRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_ProtocolVersionRequest_descriptor,
                new java.lang.String[] { });
        internal_static_tolar_proto_ProtocolVersionResponse_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_tolar_proto_ProtocolVersionResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tolar_proto_ProtocolVersionResponse_descriptor,
                new java.lang.String[] { "ProtocolVersion", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}