name: Merge to Master Build Jsongateway

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    timeout-minutes: 120
    runs-on: ubuntu-20.04

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install libxml-xpath-perl default-jre

    - name: Build artifacts
      run: |
        mvn clean spring-boot:build-image

    - name: Push artifacts to repository
      run: |
        JSON_VER=$(cat pom.xml | xpath -q -e '/project/version/text()')
        docker tag  gcr.io/tolar-devops-311210/json-gateway:$JSON_VER gcr.io/tolar-devops-311210/json-gateway:latest
        docker push gcr.io/tolar-devops-311210/json-gateway:$JSON_VER
        docker push gcr.io/tolar-devops-311210/json-gateway:latest